export * from "./IDisease";
export * from "./IPersistedModel";
export * from "./IFish";
export * from "./IPhoto";
export * from "./ITreatment";
export * from "./ITreatmentComment";
export * from "./IMeasurement";
export * from "./IPond";
export * from "./IVariety";
